#========================================================================
# Copyright 2023 Rodrigo Laiola Guimaraes
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# 
# This program is released under license GNU GPL v3+ license.
#
#========================================================================

version: "3.8"

services:
  
  # MySQL
  # https://hub.docker.com/_/mysql
  mysql5.7:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Example@1
 
  # MySQL
  # https://hub.docker.com/_/mysql
  mysql8:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Example@1

  adminer:
    image: adminer
    depends_on:
      - mysql5.7
      - mysql8
    restart: always
    ports:
      - 8080:8080
